### ISSUE TITLE
Wierd reflections and broken water texture

### ISSUE THREAD

**Issue by AirplaneA220** [FluffyDoesStuff/Fluffys-Shaded-World#1]
Reflections - [https://cdn.discordapp.com/attachments/844727267962912788/866067864309202954/unknown.png](url)
Water Texture - [https://cdn.discordapp.com/attachments/844727267962912788/866068463914451004/unknown.png](url)

**Comment by ChristianIzak** [comment]
This is a known issue and has been fixed in the latest update.
